"""
policy_schema.py
"""
POLICY_SCHEMA_VERSION = "1.0.0"

class PolicyError(Exception):
    def __init__(self, code, message):
        self.code = code
        self.message = message
        super().__init__(f"[{code}] {message}")

ERROR_FINDINGS_NOT_FOUND = "FINDINGS_NOT_FOUND"
ERROR_POLICY_REGISTRY_CORRUPTED = "POLICY_REGISTRY_CORRUPTED"
ERROR_SCHEMA_VERSION_MISMATCH = "SCHEMA_VERSION_MISMATCH"
ERROR_ARTIFACT_CORRUPTED = "ARTIFACT_CORRUPTED"
ERROR_CHECKSUM_MISMATCH = "CHECKSUM_MISMATCH"
ERROR_UNMAPPED_FINDING = "UNMAPPED_FINDING"

POLICY_TYPE_NO_APPLICABLE_POLICY = "NO_APPLICABLE_POLICY"
